version: 2.1 # Use version 2.1 to enable Orb usage.
orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  unit_tests:
    working_directory: ~/backend_app
    docker:
      - image: python:3.7.3
    steps:
      - add_ssh_keys:
          fingerprints:
            - "48:ad:63:72:59:75:00:a0:db:95:aa:95:1d:f2:c8:47" 
      - run:
          name: Run unit tests
          command: echo "Run unit test"
      - run:
          name: Clone test code
          command: git clone git@github.com:thanhpd-teko/ppm-api-testing.git
  integration_tests:
    executor: win/default
    working_directory: ~/backend_app/ppm-api-testing
    #    environment:
    #      MYSQL_DATABASE: test-ppm
    #      MYSQL_USER: dev
    #      MYSQL_PASSWORD: dev
    steps:
      - add_ssh_keys:
          fingerprints:
            - "54:0a:59:45:8a:da:a8:dc:ba:42:5c:b6:f1:14:34:c4"
#      - run:
#          name: Add ssh-keyscan
#          command: ssh-keygen -R github.com
      - run:
          name: Clone test code
          command: git clone git@github.com:Lannt-teko/ppm-api-testing.git
      #      - restore_cache:
      #          key: pip-{{checksum "requirements.txt"}}
      #      - run: python -m pip install --upgrade pips
      - run:
          name: Install requirements and run tests
          command: |
            cd intergration_test
            pip install -r requirements.txt
            pytest --submit-tests tests/functional/price/test_create_overlap_price_schedule.py
      #      - save_cache:
      #          key: pip-{{checksum "requirements.txt"}}
      #          paths:
      #            - ~/.cache/pip
workflows:
  version: 2.1
  build-test:
    jobs:
      - unit_tests
#      - integration_tests

